version: "3"

services:
  app:
    build: .
    ports:
      - "${APP_PORT:-8000}:3000"
    environment:
      MONGO_URL: mongo:27017
      REDIS_URL: redis://redis:6379
      ADMIN_EMAIL: admin@labman.local

  mongo:
    image: mongo
    ports:
      - 27017
    volumes:
      - dbstore:/data/db

  redis:
    image: redis:alpine
    ports:
      - 6379

  sidekiq:
    image: labman_app
    command: sidekiq
    environment:
      MONGO_URL: mongo:27017
      REDIS_URL: redis://redis:6379

volumes:
  dbstore:
    external: true
