sync_apps_job:
  cron: "1 * * * *"
  class: "SyncAppsJob"
  queue: sync
sync_branches_job:
  cron: "*/10 * * * *"
  class: "SyncBranchesJob"
  queue: sync
sync_merge_requests_job:
  cron: "*/15 * * * *"
  class: "SyncMergeRequestsJob"
  queue: sync
sync_issues_job:
  cron: "*/10 * * * *"
  class: "SyncIssuesJob"
  queue: sync
sync_releases_job:
  cron: "1 * * * *"
  class: "SyncReleasesJob"
  queue: sync
sync_builds_job:
  cron: "*/5 * * * *"
  class: "SyncBuildsJob"
  queue: sync
