sync_apps_job:
  cron: "*/10 * * * *"
  class: "SyncAppsJob"
  queue: sync
sync_branches_job:
  cron: "*/5 * * * *"
  class: "SyncBranchesJob"
  queue: sync
sync_issues_job:
  cron: "*/5 * * * *"
  class: "SyncIssuesJob"
  queue: sync
sync_releases_job:
  cron: "*/10 * * * *"
  class: "SyncReleasesJob"
  queue: sync
