# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2f5709fa91f65b2728d3f2a0bea2acef54f93f9904723222f1245cb8d709e9a763fb3858c75226d79cabf6330f6e580eb67f9e33e168b4c134e99d36de07ee57

test:
  secret_key_base: 958ae24586a5daa86b0c2e3222dcea389306b041375614d3671af58bf72791d2dddcaf4d78ddb64507ec534bfbd55dc24e6d733f0270703ef0e663c86f2dc26c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
